/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme')
module.exports = {
  content: [
    './Sablona/Components/**/*.{html,js}',
    './Sablona/Modules/**/*.{html,js}',
    './Sablona/Templates/**/*.{html,js}'
  ],
  safelist: [
    ...[...Array(12).keys()].flatMap(i => [`grid-cols-${i + 1}`, `md:grid-cols-${i + 1}`]),
    'bottom-triangle-left',
    'bottom-triangle-right',
    'top-triangle-left',
    'top-triangle-right',
    'bg-white',
  ],
  corePlugins: {
    container: false,
  },
  theme: {
    screens: {
      'sm': '425px',
      'md': '992px',
      'lg': '1280px',
      'xl': '1440px',
    },
    fontFamily: {
      sans: ['Montserrat', ...defaultTheme.fontFamily.sans],
      'blog': ['Proxima Nova', ...defaultTheme.fontFamily.sans],
    },
    fontSize: {
      h1: 'var(--h1-desktop)',
      h2: 'var(--h2-desktop)',
      h3: 'var(--h3-desktop)',
      h4: 'var(--h4-desktop)',
      h5: 'var(--h5-desktop)',
      h6: 'var(--h6-desktop)',
      p: 'var(--p-desktop)',
      caption: 'var(--p-caption)',
      'h1-blog': 'var(--h1-blog)',
      'h2-blog': 'var(--h2-blog)',
      'h3-blog': 'var(--h3-blog)',
      'h4-blog': 'var(--h4-blog)',
      'h5-blog': 'var(--h5-blog)',
      'h6-blog': 'var(--h6-blog)',
      'li-blog': 'var(--li-blog)',
      'p-blog': 'var(--p-blog)',
      'h1-blog-mobile': 'var(--h1-blog-mobile)',
      'h2-blog-mobile': 'var(--h2-blog-mobile)',
      'h3-blog-mobile': 'var(--h3-blog-mobile)',
      'h4-blog-mobile': 'var(--h4-blog-mobile)',
      'h5-blog-mobile': 'var(--h5-blog-mobile)',
      'h6-blog-mobile': 'var(--h6-blog-mobile)',
      'li-blog-mobile': 'var(--li-blog-mobile)',
      'p-blog-mobile': 'var(--p-blog-mobile)',
      'h1-mobile': 'var(--h1-mobile)',
      'h2-mobile': 'var(--h2-mobile)',
      'h3-mobile': 'var(--h3-mobile)',
      'h4-mobile': 'var(--h4-mobile)',
      'h5-mobile': 'var(--h5-mobile)',
      'h6-mobile': 'var(--h6-mobile)',
      'p-mobile': 'var(--p-mobile)',
      'caption-mobile': 'var(--p-caption-mobile)',
      'btn-primary': 'var(--btn-primary)',
      'btn-primary-mobile': 'var(--btn-primary-mobile)',
      'btn-secondary': 'var(--btn-secondary)',
      'btn-secondary-mobile': 'var(--btn-secondary-mobile)',
    },
    fontWeight: {
      h1: 'var(--h1-fw)',
      h2: 'var(--h2-fw)',
      h3: 'var(--h3-fw)',
      h4: 'var(--h4-fw)',
      h5: 'var(--h5-fw)',
      h6: 'var(--h6-fw)',
      p: 'var(--p-fw)',
      caption: 'var(--p-caption-fw)',
      normal: '400',
      medium: '500',
      bold: '700',
      extrabold: '800',
      'btn-primary': 'var(--btn-primary-fw)',
      'btn-secondary': 'var(--btn-secondary-fw)',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      inherit: 'inherit',
      white: '#FFF',
      grey: '#808080',
      grey2: '#F2F2F2',
      primary: 'var(--primary-color)',
      secondary: 'var(--secondary-color)',
      tertiary: 'var(--tertiary-color)',
      dark: 'var(--bg-dark)',
      light: 'var(--bg-light)',
      'btn-bg': 'var(--btn-bg)',
      'btn-text-color': 'var(--btn-text-color)',
      'btn-text-hover': 'var(--btn-text-hover-color)',
      'btn-bg-hover-light': 'var(--btn-bg-hover-light)',
      'btn-bg-hover-dark': 'var(--btn-bg-hover-dark)',
    },
    lineHeight: {
      h1: 'var(--h1-lh)',
      h2: 'var(--h2-lh)',
      h3: 'var(--h3-lh)',
      h4: 'var(--h4-lh)',
      h5: 'var(--h5-lh)',
      h6: 'var(--h6-lh)',
      p: 'var(--p-lh)',
      caption: 'var(--p-caption-lh)',
    },
    backgroundImage: {
      grain: "url('{{ get_asset_url('/Sablona/Assets/img/gb_bg_grain-min.png') }}')",
    },
    extend: {
      gap: {
        15: '3.75rem',
        'form': '1.875rem',
      },
      maxWidth: {
        'unset': 'unset',
      },
    },
  },
  plugins: [
  ],
}

